### PR TITLE
Update graphql-java to 16.1

### PR DESCRIPTION
**Pull request by williamboman-pp**
Hi :)

### CODE REVIEW

**Comment by williamboman-pp** [comment]
Would be nice to get this merged, it's currently blocking us from upgrading graphql-java-tools (& graphql-java)

**Review by lkorth — APPROVED** [review]

**Comment by lkorth** [comment]
Thanks for the update, we'll get a release out!

**Comment by williamboman-pp** [comment]
> Thanks for the update, we'll get a release out!

Sweet, thanks 😊!

**Comment by miriam** [comment]
Just published the package. It might be about 10 minutes before it's available on Maven Central. Thanks @williamboman-pp !!

**Pull request merged**
